# Custom Language File for Launcher Customizer

[ejs.app]
title = "ASMP Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/maxim-lvr/ASMP_Launcher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/maxim-lvr/ASMP_Launcher"
supportLink = "https://github.com/maxim-lvr/ASMP_Launcher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR ASMP"
welcomeDescription = "Merci Arthur pour les travaux"
welcomeDescCTA = "Let's go le FISC"
